### ISSUE TITLE
crash when posting

### ISSUE THREAD

**Issue by Chup123** [mbruel/ngPost#110]
ngPost crashes when I use usenet.farm and the speed goes up to 30 MB/S. Can't look in the log because it can't write to it. Do you know a solution?

It doesn't give an error either, but just crashes the program during posting

**Comment by mbruel** [comment]
well that's hard to debug with such minimal information.
What OS?
I suppose you use the GUI?
Is it crashing every time?
Do you have several posts in queue?
What you should try is to do ONE single quickpost and see if it crashes. Maybe just use 1 Thread.
If you want to help, you can then try to use it command line, this way you'll be able to save the log.

**Comment by mbruel** [comment]
I've added new keyword `LOG_IN_FILE` to save logs in a file. [cf here](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L133)
Let me know which OS you use, I'll build you a version before the new release.

**Comment by Chup123** [comment]
Hi, i'm using Windows 10 64 bit v20H2. 
Im using the GUI when posting, and it only crashes when using usenet.farm at files bigger than 4 gigs.
I have tried this with 1 and multiple post in the queue, doesnt make a difference.

Thanks for making this build and adding the log feature

**Comment by mbruel** [comment]
Well it doesn't make sense that the crash would be linked to a specific provider (usenet.farm...)
It is weird also that it would only happen on big files.
Do you compress the files and cut them in several volumes? which is the size of the volumes?
Can you check the memory usage plz when posting. Maybe you're running out of memory?

So here is the new version, replace the `ngPost.exe` [with this one](https://files.fm/f/kftvpbd4n).
Add `LOG_IN_FILE = true` in the ngPost.conf ([cf here](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L133))
**Please tick `show debug info` and set the level to 2**
**When you've a crash, DON'T LAUNCH ngPost again before copying the log (ngPost.log).** Otherwise it will be overwritten.
send me the log file when you get one

**Comment by mbruel** [comment]
@Chup123 any update?

**Comment by Chup123** [comment]
It doesn't crash anymore. Dont know what you changed but i'm happy!

**Comment by mbruel** [comment]
hum I didn't do any fix... just add the possibility to log in a file.
try again with the original ngPost.exe if you kept it to see if you still have the problem.
cheers
