### ISSUE TITLE
Using multiple groups to post, not working wright.

### ISSUE THREAD

**Issue by BigM001** [mbruel/ngPost#136]
I'm always using multiple groups to post, but ngPost only uses the last one.

I have configured it right, groups separated by comma and no spaces.

**Comment by mbruel** [comment]
Check the doc: https://github.com/mbruel/ngPost/blob/master/README.md#configuration-file-and-keywords-that-are-only-in-config
And the configuration file: https://github.com/mbruel/ngPost/blob/7f4762b66ceefb5016a9fa6cefd310e0d3da6936/ngPost.conf#L76
I don't really see the interest to post on several groups, that's why by default, we post randomly on ONE of the list ;)
