### ISSUE TITLE
NZB overwritten on repost

### ISSUE THREAD

**Issue by no-bdy** [mbruel/ngPost#16]
1st concern
NZB is explicitly overwritten if performing a repost, recommend rename by date on --auto or --monitor, prompt if manual. Anything except just overwrite without any notifications.

2nd concern
Recommend not using 2 separate randomFrom functions to return different types, here is a fix:
file: hmi/MainWindow.cpp function: onGenPoster, use a single call to convert from stdString
_ui->fromEdit->setText(QString::fromStdString(_ngPost->_randomFrom()));

3rd is just a request, I've already done a rewrite on the randomFrom function in NgPost.cpp to make the entire from email random:

std::string NgPost::_randomFrom() const
{
    QString randomFrom, alphabet("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_");
    int nb = 21, nbLetters = alphabet.length();
    for (int i = 0 ; i < nb ; ++i) {
        if (i==10) { randomFrom += "@"; }
        if (i==18) { randomFrom += "."; }
        randomFrom.append(alphabet.at(std::rand()%nbLetters));
    }
    return randomFrom.toStdString();
}

This makes the from email a random(10) string at random(8) string dot random(3) string.

4th is a suggestion
Instead of requiring "--compress" for --monitor and --auto then failing if it's not included, I recommend a _log("Warning: --compress automatically selected for --auto operation"); then just enable compression for the user anyway, since it's required, then proceed without return false;

Apologies is toes are stepped on here, I like what you've put together thus far keep up the good work.

**Comment by no-bdy** [comment]
Update: Noted use of random From results in a different poster per file instead of per NZB, this should be looked into as it doesn't index the post properly on a search engine.

**Comment by mbruel** [comment]
>  NZB is explicitly overwritten if performing a repost, recommend rename by date on --auto or --monitor, prompt if manual. Anything except just overwrite without any notifications.

yeah true, I might do that. It's also problematic if for some reason you launch several instances of ngPost...


>  Recommend not using 2 separate randomFrom functions to return different types, here is a fix

well that's a bit a shame to use QString::fromStdString no a QString("@%1.com").arg(_articleIdSignature.c_str()).toStdString();
but yeah, it is only used by the HMI so not such a big deal...

I wouldn't want to use the opposite for efficiency as NgPost::_randomFrom could be called quite often if Article obfuscation is ON.


> This makes the from email a random(10) string at random(8) string dot random(3) string.

Well I like the fact to let the ngPost or user fixed signature on the Article signature and poster. Most other soft does the same. Maybe I could just let it for the Articles and make it random for the poster...


>  Instead of requiring "--compress" for --monitor and --auto then failing if it's not included, I recommend a _log("Warning: --compress automatically selected for --auto operation"); then just enable compression for the user anyway, since it's required, then proceed without return false;

I prefer NOT do things without the user perfectly knowing it, so I prefer the user to explicitly write the --compress. Just use an alias if you need...


> Apologies is toes are stepped on here, I like what you've put together thus far keep up the good work.
Cheers ;)


> Update: Noted use of random From results in a different poster per file instead of per NZB, this should be looked into as it doesn't index the post properly on a search engine.

yeah that's why I removed the option and just let it for the Article Obfuscation mode that provide complete invisibility of your posts. If you wish to find your post in main indexer, you shouldn't use that option you and stick with ONE random Poster for the whole nzb.

**Comment by mbruel** [comment]
I've pushed a fix to not overwrite nzb file for monitoring (both HMI and CMD) and auto posting (only CMD)

```
commit f95207a1cbcd50eafa54bc89befebd39a2b2a586 (HEAD -> master, origin/master, origin/HEAD)
Author: Matthieu Bruel <Matthieu.Bruel@gmail.com>
Date:   Wed Feb 5 12:07:24 2020 +0000

    Don't overwrite nzb file for monitoring (or --auto in CMD)
    refactoring randomFrom functions and making them inlines
```

**Comment by no-bdy** [comment]
Excellent.
