### ISSUE TITLE
[Request] Set default password for --Auto --Monitoring.

### ISSUE THREAD

**Issue by kDipak** [mbruel/ngPost#26]
Hello Matthieu,

I would like to request an option to set a default password when using the --auto and --monitoring switch.

**Comment by mbruel** [comment]
this has been implemented. you can now use --rar_pass instead of --gen_pass with --auto and --monitor to provided a fixed password for all the postings.
If you put both --rar_pass and --gen_pass, --gen_pass will overwrite --rar_pass.
I've built [the exe for win64 ](https://files.fm/u/p8er6vzf)for you to try, let me know if it works as expected and if so, please close this request ;)
Cheers!

**Comment by kDipak** [comment]
works as advertised :) 

Thanks for the quick response 💯

**Comment by mbruel** [comment]
you're welcome ;)
