### ISSUE TITLE
Raspberry Pi - How to install rar?

### ISSUE THREAD

**Issue by DarkShadowxx** [mbruel/ngPost#27]
I just downloaded ngPost on my RPi, but I wonder how I install rar?
It seems to be not available for ARM: https://www.rarlab.com/download.htm
In case it is not possible: is there any alternative I can use with ngPost for creating rars?

**Comment by mbruel** [comment]
Yep rar is not available on RPI. That's why I've added the support of 7zip.
- Install 7zip (package p7zip-full)
- edit ~/.ngPost and set RAR_PATH to point on it and uncomment RAR_EXTRA to use 7z syntax.
You should have something like this:
```
## RAR or 7zip absolute file path (external application)
## /!\ The file MUST EXIST and BE EXECUTABLE /!\
## this is set for Linux environment, Windows users MUST change it
#RAR_PATH = /usr/bin/rar
RAR_PATH = /usr/bin/7z

## RAR EXTRA options (the first 'a' and '-idp' will be added automatically)
## -hp will be added if you use a password with --gen_pass, --rar_pass or using the HMI
## -v42m will be added with --rar_size or using the HMI
## you could change the compression level, lock the archive, add redundancy...
#RAR_EXTRA = -ep1 -m0 -k -rr5p
RAR_EXTRA = -mx0 -mhe=on   (for 7-zip)
```

I didn't double check but it should still work. I gonna add a note on the README about that ;)
Please confirm if it works.
Cheers

**Comment by DarkShadowxx** [comment]
Thanks.
I just tried it out, but got an error message:

```
pi@raspberrypi:~/nextcloud $ /home/pi/Downloads/ngPost_v4.4-armhf.AppImage -s -h *** -P 443 -u *** -p *** -x -g alt.binaries.test -t 2 -n 10 --tmp_dir /home/pi/nextcloud/tmp --rar_size 5 --par2_pct 10 --compress --par2_path /usr/bin/par2 --rar_path /usr/bin/7z --gen_name --length_pass 32 --gen_pass --disp_progress BAR --gen_par2 -o test.nzb -i 100mbtest.bin 

ERROR loading translator :/lang/ngPost_en.qm
ERROR: couldn't find translator for lang en
Using default config file:  "/home/pi/.ngPost"
Do article obfuscation (the subject of each Article will be a UUID)

Beginne mit Posting: test.nzb
Dateien komprimieren: /usr/bin/7z a -mx0 -mhe=on -pZS4qRCoPPs9OxaGnnESG7IIPlt2d9uDZA5DR7pfLWeZJ2fuehAkeHqusYkLXSOuR -v5m /home/pi/nextcloud/tmp/20NAre42CSfnm1S2k/20NAre42CSfnm1S2k.7z /home/pi/nextcloud/100mbtest.bin
**

Erzeugen von Par2: /tmp/.mount_ngPostj2KWnP/par2 c -l -m1024 -r10 /home/pi/nextcloud/tmp/20NAre42CSfnm1S2k/20NAre42CSfnm1S2k.par2 /home/pi/nextcloud/tmp/20NAre42CSfnm1S2k/20NAre42CSfnm1S2k*rar -q
You must specify a list of files when creating.

Fehler während par2 Generierung: 3
=> Anwendung schließen
ngPost closed propertly!

```

**Comment by mbruel** [comment]
ok, I've corrected the issue.
I'[ve built a new AppImage](https://github.com/mbruel/ngPost/raw/master/release/ngPost_v4.4.1-armhf.AppImage). Please give it a try.
I've included parpar binary in the AppImage, I strongly advise you to use it, it's at least 4 times faster.
To do so, Edit ~/.ngPost and set:
```
PAR2_PATH = ./parpar

## fixed parameters for the par2 (or alternative) command
## you could for exemple use Multipar on Windows
PAR2_ARGS = -s5M -r8% -m1024M --progress stdout -q
```

At the moment, when using parpar, you can't set the percentage of redundancy in the command line, it is fixed in the config file. I'll change that in the next release.
So you command should only be something like this:
```
pi@raspberrypi:~/ngPost $ ./ngPost_v4.4.1-armhf.AppImage -s -h $NG_SRV -P 443 -u $NG_USER -p $NG_PASS -x -g alt.binaries.test -t 2 -n 10 --tmp_dir /tmp --rar_size 5 --compress --gen_name --length_pass 32 --gen_pass --disp_progress BAR --gen_par2 -o test3.nzb -i ngPost_v4.4.1-armhf.AppImage
```

**Be careful using the -x option!** Have you understood what it does? you won't be able to find your post without the nzb. The indexers won't find your posts. It is useless to use --gen_name --length_pass 32 --gen_pass when -x is on.



> EDIT: I wonder if filenames are encrypted as well when using encryption with 7z?

what do you mean? renaming the files inside the archive? it should be yeah. But again no point using it if you use -x...

Please confirm if everything is working with [this 4.4.1 version](https://github.com/mbruel/ngPost/raw/master/release/ngPost_v4.4.1-armhf.AppImage).

and feel free to give a [small contribution to reward the support](https://github.com/mbruel/ngPost#donations) ;)

**Comment by DarkShadowxx** [comment]
I just downloaded it and changed my config, but now it says the following:

```
[...]
Erzeugen von Par2: /tmp/.mount_ngPostLP8hqx/par2 -s5M -r8% -m1024M --progress stdout -q /home/pi/nextcloud/tmp/LSMHUDuk06t9qKTrx/LSMHUDuk06t9qKTrx.par2 /home/pi/nextcloud/tmp/LSMHUDuk06t9qKTrx/LSMHUDuk06t9qKTrx.7z*
Invalid operation specified: -s5M

Fehler während par2 Generierung: 3
=> Anwendung schließen
ngPost closed properly!
```

And yes, I do want the files to be accessible with the .nzb and the password only.

When using WinRar, you can specify if the file names should be encrypted. If you do so, you can't see the filenames without the password. If you don't, you can see all the file names (without their contents).

PS I donated you a coffee ;)

**Comment by mbruel** [comment]
you're using par2cmdline as application but parpar parameters.
remove --par2_path from you cmd and set it in the config file.
It should then work.

Yes you can encrypt with 7z and it is done properly when you use --gen_pass or --rar_pass.
cf the 7z command: 
`Compressing files: /usr/bin/7z a -mx0 -mhe=on -pWNCd6vKjKSuAP24JzoZYgW1ZDIGGssTC -v5m /tmp/HKz7K456uQl37c5tRqFmoP/HKz7K456uQl37c5tRqFmoP.7z /home/pi/ngPost/ngPost_v4.4.1-armhf.AppImage`
-pWNCd6vKjKSuAP24JzoZYgW1ZDIGGssTC is for the password.
-mhe=on is to encrypt also the header (so you can't list the files without the password)
-mx0 is to don't compress at all, just store.

Thanks for the coffee ;)

**Comment by DarkShadowxx** [comment]
Hmm, I have set the path in my config:
```
PAR2_PATH = ./parpar
PAR2_ARGS = -s5M -r8% -m1024M --progress stdout -q
```
and is the command I used:
```
./ngPost_v4.4.1-armhf.AppImage -s -h *** -P 443 -u *** -p *** -g alt.binaries.test -t 2 -n 10 --tmp_dir /home/pi/nextcloud/tmp --rar_size 5 --compress --gen_name --length_pass 32 --gen_pass --disp_progress BAR --gen_par2 -o test.nzb -i ngPost_v4.4.1-armhf.AppImage
```

**Comment by mbruel** [comment]
what's the par2 command? (Generating par2)

**Comment by DarkShadowxx** [comment]
Here is the output from generating the par:
```
Erzeugen von Par2: /tmp/.mount_ngPosts5eHB5/par2 -s5M -r8% -m1024M --progress stdout -q /home/pi/nextcloud/tmp/lMzn4o9awYggEb8r2/lMzn4o9awYggEb8r2.par2 /home/pi/nextcloud/tmp/lMzn4o9awYggEb8r2/lMzn4o9awYggEb8r2.7z*
Invalid operation specified: -s5M
```

Yes, I did edit ~/.ngPost. I have uploaded it to [pastebin](https://pastebin.com/SwXrgTLR).

Using --par_path results in an error:
```
Using default config file:  "/home/pi/.ngPost"
Fehlersyntax: Unknown option 'par_path'.
Um die verfügbaren Optionen aufzulisten, verwenden Sie: ./ngPost_v4.4.1-armhf.AppImage --help
```

**Comment by mbruel** [comment]
it's --par2_path. give it a try... (--par2_path ./parpar)
That's weird...
Otherwise download the parpar binary  but it but it should work... it is included in the AppImage, the size is much bigger!
I'll give it a try again later tonight or tomorrow...
For the parpar binary, you [can find it here](https://github.com/animetosho/ParPar/files/4136205/parpar.xz.zip), you need to unzip then unxz. once double unpacked, try to give the full path using --par2_path

**Comment by mbruel** [comment]
About your config file:
If you've set the server there, no need to give it in the command line.
you could set the TMP_DIR there also.
and also LENGTH_NAME and LENGTH_PASS
uncomment also DISP_Progress = BAR ;)

So your command could just be:
`./ngPost_v4.4.1-armhf.AppImage  -g alt.binaries.test --rar_size 5 --compress --gen_name --gen_pass --gen_par2 -o /full_path/test.nzb -i ngPost_v4.4.1-armhf.AppImage`

**Comment by DarkShadowxx** [comment]
Seems to work when using their binary. Thanks!
Maybe you can check that on an own Pi and fix it in the next update.

PS Yes I could have used the command without some params, but I wanted you to know all options I use ;)
