### ISSUE TITLE
Quick Post pack multi files into a single post

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ngPost#37]
Thanks for the update and YES the 4.5 version fixed all problem i have except this one or this might be made this way, im not sure.

Quick Post pack multi files from different folders into a single post

is there is anyway to have an option to pack each file into a single post .

or should we keep it that way so the quick post will pack all files into a single file and Auto Posting will pack each file or each folder into its own post ? however quick post split folder one for each post .

maybe be good if there is options to choose from for each type of post , thanks  .. you are da man :)

**Comment by mbruel** [comment]
I'm not to understand what you'd like.
But yeah that's the idea, Quick Post doesn't separates files/folder, it post all of them in a single NZB file. You can (or not) use compression. Basically that's the -i option in command line. That is mainly for people who wants to use ngPost only as a poster but do their own compression and obfuscation with a script.

Auto Post is there to makes things faster and be able to generate Quick Post for each individual File or Folder. I've adding drag and drop support and the right click. So you could put all the movies you'd like to post and then just click to "Generate Post"

I don't see the benefit to be able to put all of them in ONE NZB file on the AUto Post. If you want to do that, do it in a Quick Post tab.

What am I missing?

**Comment by DEVUVO** [comment]
Alright let me try to be more clear , i understand now the quickpost is for packing the while thing what you dropped there ... BUT it does separate the folder and pack each folder on a single post , maybe you already know maybe NOT , that's why it did confuse me.

if you have done it this way i will clone this issue , thanks everything so far works great .

**Comment by mbruel** [comment]
> BUT it does separate the folder and pack each folder on a single post

I still don't get that...

**Comment by DEVUVO** [comment]
Okay let me be more clear , sorry about the delay it was for a reason i had to do a deeper test for the app and here is what i found out that maybe you can make it easier for all of us or maybe at least me for now , 
this is about latest version v4.5
1 - quick post have few issues , first when i add a few folders and few videos , I see if the app does use winrar in the wrong way when it compress the file

the app using winrar to compress files and folders all together without any folder names this is very bad and will cause troubles if the files names have the same names if the each folder have a unique crc files but the files inside all folders have the same name , it will pack all in one rar without any folder

2 - after the upload is done in quick post , i have to close and reopen the app so it will pick up the auto compress setting otherwise it will keep posting what i add with it's original name

for example

I have 3 files , or 3 folder , when the app completed the upload with the correct setting and i have to remove the files or folder from the apps list to add more files it will change the setting and the rars names to the first file or first folder in the list . but the auto posting has no problem with remembering the setting


3 - About the tab per each post its very annoying , maybe you can make the status inside the list where we drop the files or folders so it will not take so long if uploading 4000 folder or more it does affect the speed and i understand you did a lot of work closing the tab after each completed post

To be more clear it's like 
c:/users/admin/download/video0411/BR.rty

so after its done uploading maybe better to not open a new tab for it but keep the progress on the right corder as its now and it will be like

c:/users/admin/download/video0411/BR.rty ...... Done with green color , or red color if there is a problem

4 - A check box to rename or overwrite the new NZB for the files or folders , or maybe add timestamp for NZB files while upload files with same name ,

overwrite or timestamp as option not by default instead of asking me

NOTE : I wish you can add [ Remove All ] button like the one on the quick post

I know it's maybe not easy but these are important I'm still testing but so far there is nothing to complain about , no other issues at the moment . i will post it here as reply so i dont have to open a new issue .  i hope you don't mind working on and fix these issues. 

Thanks in advance.

**Comment by mbruel** [comment]
> the winrar will pack all the files together however will keep sub folders packed without the parent folder , i hope you understand .

Ah ok I got it. Well nobody normally do that... You either post a single file (movie or iso) or a single folder (scene release or dvd or ?)
I removed the the parent folder on request as it is quite boring to have it twice when you download. Cause the download soft will create the root folder.
I understand, the problem is when you put several folders or mix it with files...
Well what is the use case? When/why would you like to do that?

> I have 3 files , or 3 folder , when the app completed the upload with the correct setting and i have to remove the files or folder from the apps list to add more files it will change the setting and the rars names to the first file or first folder in the list . but the auto posting has no problem with remembering the setting

Well that's normal. If you have the Auto Compress ticked in the parameters, it will generate a new random name. There is a bug, it is not doing it now, I'm correcting it. If you don't have the Auto Compress ticked, it will put the name of the first file.


>  3 - About the tab per each post its very annoying , maybe you can make the status inside the list where we drop the files or folders so it will not take so long if uploading 4000 folder or more it does affect the speed and i understand you did a lot of work closing the tab after each completed post

who would post 4k folders? oO
The goal of the GUI is to be visual and make it easier of occasional posters. I think most of them are happy with the Tabs. You can see the individual posts and cancel them.
I've added the Auto Close option for those sending hundreds of files...
This shouldn't impact the app speed so much.
But anyway, for those usage, you should use the CMD instead with --auto.
It's quite easy! 
`ngPost.exe --auto C:\tmp\myDirectory` if you've the AUTO_COMPRESS in the conf file.

Otherwise you may detail all the options:
`ngPost.exe --auto C:\tmp\myDirectory --disp_progress bar --compress --gen_name --gen_pass --gen_par2`


> 4 - A check box to rename or overwrite the new NZB for the files or folders , or maybe add timestamp for NZB files while upload files with same name ,

This is done for the monitoring and all the time in Command Line. Again, when you've a GUI, it's for the user to get the questions and answer them ;)
Plus you're not supposed to post the same thing twice!... what's the point? oO
There are no space left on the GUI for another checkbox. I could add a config... but then people using the GUI won't see it...


> 5 NOTE : I wish you can add [ Remove All ] button like the one on the quick post

The original idea was just to use the SCAN button on a single directory (the Auto Dir) so there was no point.
Not much space to add a Clear button.
You can do Ctrl+A then DEL... it's quite fast... probably faster than moving the mouse no?

**Comment by mbruel** [comment]
> 2 - after the upload is done in quick post , i have to close and reopen the app so it will pick up the auto compress setting otherwise it will keep posting what i add with it's original name

You don't have to close the app. Just click on the button to generate a new name...

**Comment by mbruel** [comment]
I've introduced a new config: RAR_NO_ROOT_FOLDER that is off by default.
So your point 1 should be OK now.

[You can try this pre-release](https://files.fm/f/jw3a5ju5). Let me know what you think.
Your point 2 should also be corrected.

3 and 4 I won't do for now.
Open separate REQUESTs ticket to keep track of them and see if other people would be interested.
Cheers.

PS: If point 1 and 2 are solved, please close this issue.

**Comment by DEVUVO** [comment]
1 & 2 issues are now done . issues closed .
