### ISSUE TITLE
Average speed measuring continues when upload is paused

### ISSUE THREAD

**Issue by peskdale** [mbruel/ngPost#64]
When you pause an upload, the average speed continues to be measured at the bottom-right of the GUI. This causes the indicated speed to be lower than expected when the upload is later resumed.

Related feature request: it would be great for the GUI to have a more immediate short-term speed indication to go alongside the total average. e.g. _Average speed over last 10 seconds_. This is helpful when trying to manage network load, or diagnose possible upload speed issues.

**Comment by mbruel** [comment]
yeah I know, I don't break the timer when people pause...
you're not really supposed to pause that often. in general when you want to post, you just let the stuff run. if in any case you forgot to check something, then cool, you can pause, that's why I've added it but it shouldn't be everyday...
it sounds a bit complicated to take it in consideration... I'll see if I can find an easy way.

For the current speed, indeed it could be interesting... Idem, it's some work, I need to find the time...
Create a separate Request Thread, we'll see if other people would be interested.

**Comment by mbruel** [comment]
I've implemented a simple way to remove the time when ngPost is in pause from the avg speed.
I didn't test but it should work... I let you tell me ;)
I'm going to close this issue.
@peskdale plz open a new Request issue for the "immediate" speed

**Comment by peskdale** [comment]
This seems to work. Paused an upload, waited a little bit, then resumed. The speed calculation was corrected as expected.

The GUI does show a decreasing speed while paused. That could be fixed by adding `        if (_activeJob && !_activeJob->isPaused())` to [this block of code](https://github.com/mbruel/ngPost/blob/master/src/NgPost.cpp#L431), effectively freezing the readings.

**Comment by mbruel** [comment]
I'd rather do it properly and stop triggering onRefreshprogressbarBar.
and start again on resume.
time for bed, I'll check that tomorrow
