### ISSUE TITLE
Scrollbar for Upload-Tabs

### ISSUE THREAD

**Issue by l0co666** [mbruel/ngPost#76]
When i start an AutoPost with much Folders, than the width of the ngPost-Window becomes to big for my screen :)

I think a Scrollbar for the Upload-Tabs is an awesome feature ! Or a List of the Uploads-Tabs (with scrollbar) on an other position is would be also great

(MacOS-Client)

**Comment by mbruel** [comment]
Hi,
There should be two bottons at the extreme right of the all the tabs to go left and right in the Tabs.
It is also possible to scroll using the mouse or two fingers. It's working well on Linux, it should also on Mac and Windows but I didn't try.
You can click several times on New to create lots of empty Quick Post and give it a try. Thanks to let me know if there is an issue.
I can't add a scrollbar out of the box as I don't think the [QTabWidget](https://doc.qt.io/qt-5/qtabwidget.html) provides that feature.

**Comment by l0co666** [comment]
![screen](https://user-images.githubusercontent.com/38340883/94341274-3a225900-0008-11eb-9b4b-72525d72e280.png)

**Comment by mbruel** [comment]
ok I've check on my MacOS VM and indeed the tabs are not scrollable by default...
I've forced the option and now it should be ok. The fix will be included in the next release. I may work on it this weekend otherwise it will be for the beginning of October.

![ngPost_MacOS_scrollbar_uploadTabs](https://user-images.githubusercontent.com/14995455/94342461-69899380-0011-11eb-9ff3-81d74894494f.png)

**Comment by l0co666** [comment]
Wow ! Thank you! And thank you for this awesome app
