### ISSUE TITLE
ngPost available via npm like parpar

### ISSUE THREAD

**Issue by noobcoder1983** [mbruel/ngPost#89]
Would it be possible to provide ngPost with the help of npm manager like for example parpar (https://github.com/animetosho/ParPar) with:

`npm install -g @animetosho/parpar`

in a similar way?

Thanks.

**Comment by mbruel** [comment]
Npm is for Node.js...
I could build a .deb or a .run but I don't know how to it... Ideally I'd like to be part of the distro repository like nzbget did but again, I'd need some help or loose lots of time...

I'm going to take soon the Apple developer licence so I could try to put ngPost in the appstore but I'm not sure it would be accepted and how it works to not duplicate QT libraries... Not sure Mac did something clever. Maybe Brew. But I guess I'll end up making the .deb ;)

**Comment by noobcoder1983** [comment]
Oh ok thats correct only works for Node.js. Ok for Mac OS brew is maybe better. The windows installer always worked for me. 

But https://brew.sh/ is also available for linux maybe that is a solution.

And for Windows maybe https://chocolatey.org/packages is an alternative.

**Comment by mbruel** [comment]
> But https://brew.sh/ is also available for linux maybe that is a solution.

there is absolutely no point to use brew on Linux. It has been created for Mac in order to have a packet manager like all Linux distro use and so to install easier Linux apps without the need of the AppStore.
The dmg I'm publishing is working well, I don't have time to loose to understand how brew works.
If someone has the knowledge, I'm glad if he does it ;)



> And for Windows maybe https://chocolatey.org/packages is an alternative.

Same the installer is working great. I'm not using Windows since XP. I've a Win7 Virtual  Machine but I just use it to build my apps.
From what I know, on win10 you can have Linux. So I suppose that if ngPost is released on Debian repository, it will be available this way for Windows too. Same, I've no time to loose on an OS I definitely don't promote.
